apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: registry.gitlab.com/bp-sojka/mppa/pucil-majetek:latest
          imagePullPolicy: Always
          env:
            - name: NETTE_DEBUG
              value: "1"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 80
