services:
  php:
    container_name: bp
    image: bp_php
    build: build/php
    volumes:
      - ../:/var/www/html
    ports:
      - 80:80
    environment:
      - NETTE_DEBUG=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - database
    links:
      - database
      - redis
    networks:
      - bp-network

  database:
    container_name: bp_db
    image: mariadb:11.6.2
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=bp
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=bp
    volumes:
      - bp-datavolume:/var/lib/mysql
    networks:
      - bp-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_bp
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_USER=bp
      - PMA_PASSWORD=test
    networks:
      - bp-network

  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - bp-network

  grafana:
    image: grafana/grafana:11.3.1
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - bp-network
  prometheus:
    image: prom/prometheus:v3.0.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bp-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=test
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - bp-network
volumes:
  bp-datavolume:
  redis_data:
  elastic_data:

networks:
  bp-network: